

import { UserProfile, UserRole } from '../types';

export const MOCK_USERS: UserProfile[] = [
  { 
    uid: 'vereador-1', 
    name: 'IRMÃO BETO', 
    party: 'PP', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-1',
    email: 'irmao.beto@sapv.gov',
    role: UserRole.PRESIDENTE,
    boardRole: 'Presidente',
  },
  { 
    uid: 'vereador-2', 
    name: 'FRANCIS DE GINALDO', 
    party: 'MDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-2',
    email: 'francis.ginaldo@sapv.gov',
    role: UserRole.VEREADOR,
    boardRole: 'Vice-Presidente',
  },
  { 
    uid: 'vereador-3', 
    name: 'SARGENTO VAL', 
    party: 'MDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-3',
    email: 'sargento.val@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-4', 
    name: 'MANOEL DO POSTO', 
    party: 'PP', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-4',
    email: 'manoel.posto@sapv.gov',
    role: UserRole.VEREADOR,
    boardRole: '1º Secretário',
  },
  { 
    uid: 'vereador-5', 
    name: 'JULIANA VIDAL', 
    party: 'PP', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-5',
    email: 'juliana.vidal@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-6', 
    name: 'DEL DO MERCADINHO', 
    party: 'PSDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-6',
    email: 'del.mercadinho@sapv.gov',
    role: UserRole.VEREADOR,
    boardRole: '2º Secretário',
  },
  { 
    uid: 'vereador-7', 
    name: 'JOÃO OLÍMPIO', 
    party: 'PSB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-7',
    email: 'joao.olimpio@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-8', 
    name: 'DANIEL MIGUEL', 
    party: 'PSDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-8',
    email: 'daniel.miguel@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-9', 
    name: 'JOÃO SUFOCO', 
    party: 'UB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-9',
    email: 'joao.sufoco@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-10', 
    name: 'LÊDO', 
    party: 'PSDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-10',
    email: 'ledo@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-11', 
    name: 'CHICO DO POVO', 
    party: 'MDB', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-11',
    email: 'chico.povo@sapv.gov',
    role: UserRole.VEREADOR,
  },
  { 
    uid: 'vereador-12', 
    name: 'ADRIANO FERREIRA', 
    party: 'PODE', 
    photoUrl: 'https://i.pravatar.cc/150?u=vereador-12',
    email: 'adriano.ferreira@sapv.gov',
    role: UserRole.VEREADOR,
  },
  // Non-council members
  {
    uid: 'secretaria-1',
    name: 'Maria Silva',
    party: '',
    photoUrl: 'https://i.pravatar.cc/150?u=secretaria-1',
    email: 'secretaria@sapv.gov',
    role: UserRole.SECRETARIA,
  },
  {
    uid: 'controlador-1',
    name: 'Carlos Andrade',
    party: '',
    photoUrl: 'https://i.pravatar.cc/150?u=controlador-1',
    email: 'controlador@sapv.gov',
    role: UserRole.CONTROLADOR,
  },
  {
    uid: 'publico-1',
    name: 'Cidadão Exemplo',
    party: '',
    photoUrl: 'https://i.pravatar.cc/150?u=publico-1',
    email: 'publico@sapv.gov',
    role: UserRole.PUBLICO,
  },
  {
    uid: 'suporte-root',
    name: 'Suporte Técnico',
    party: '',
    photoUrl: 'https://i.pravatar.cc/150?u=suporte-root',
    email: 'root@sapv.gov',
    role: UserRole.SUPORTE,
  }
];